#!/bin/sh

if [ -z "$1" ]; then
  echo "ERR: No commit message file provided."
  exit 1
fi

npx --no-install commitlint --edit "$1" || {
  echo "ERR: Invalid commit message."
  exit 1
}

echo "OK: Commit message is valid."